"""enforce IOC uniqueness

Revision ID: 0d6510a65636
Revises: a6e331180fda
Create Date: 2026-09-01 21:14:01.698260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6510a65636'
down_revision: Union[str, Sequence[str], None] = 'a6e331180fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_ioc_type_normalized_value', 'iocs', ['indicator_type', 'normalized_value'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ioc_type_normalized_value', 'iocs', type_='unique')
    # ### end Alembic commands ###
