"""add IOC temporal tracking

Revision ID: a6e331180fda
Revises: b7df0d318726
Create Date: 2026-09-01 20:49:05.532618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e331180fda'
down_revision: Union[str, Sequence[str], None] = 'b7df0d318726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iocs', sa.Column('first_seen', sa.DateTime(), nullable=True))
    op.add_column('iocs', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iocs', 'last_seen')
    op.drop_column('iocs', 'first_seen')
    # ### end Alembic commands ###
